### ISSUE TITLE
Could you please upload source code of "Learning a Fine-Grained Review-based Transformer Model for Personalized Product Search"

### ISSUE THREAD

**Issue by rucliujn** [kepingbi/ProdSearch#1]
I read your paper "Learning a Fine-Grained Review-based Transformer Model for Personalized Product Search" and there is a link to this repository. However, I find codes in this repository are actually the model in "A Transformer-based Embedding Model for Personalized Product Search".
Could you please upload the source code? Thanks so much!!

**Comment by kepingbi** [comment]
This repository also has the code of RTM for the paper "Learning a Fine-Grained Review-based Transformer Model for Personalized Product Search". Using --model_name "review_transformer" instead of "item_transformer" will run RTM instead of TEM. Sorry for the inconvenience. I'll update the instructions later when I got a chance.

**Comment by rucliujn** [comment]
Thank you!
